### ISSUE TITLE
Client::authoriseAccount method name is misspelled

### ISSUE THREAD

**Issue by ehlersd** [cwhite92/b2-sdk-php#6]
Should be authorizeAccount (with a 'z') in Client.php, both in the comment and method definition (Lines 398 & 402), as well as when it's called on line 37.

**Comment by matslindh** [comment]
I've added a PR to fix this. I suggest doing a release afterwards so we can get a proper version with the previous fix installable through composer.

**Comment by cwhite92** [comment]
Thanks @matslindh! I've been inactive on this due to being very busy at work. I've just merged your PR and I'll tag a new release shortly.
